name: Non-regression testing, with multiple python versions

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: "ubuntu-latest"
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "pypy2.7", "pypy3.9"] # , "graalpy-22.3"]
        # this graalpy does not find miasmX to import, but work on my computer
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install pytest coverage codecov
    - name: Non-regression test
      run: |
        coverage run -a -m pytest
    - name: Update codecov
      run: |
        codecov
